### ISSUE TITLE
API backend: REST API

### ISSUE THREAD

**Issue by IceKhan13** [IceKhan13/purplecaffeine#10]
Implement restful api for `APIBackend` to store Trials in remote application.

Epic https://github.com/IceKhan13/purplecaffeine/issues/2

**Comment by mickahell** [comment]
Do you have a design in mind or does it just a local REST API (based on localhost) using Flask or similar ?

**Comment by IceKhan13** [comment]
it is restful service which can be hosted anywhere. 
Yes, we will use python based framework. Probably Django as majority of our team is familiar with it

**Comment by AnsahMohammad** [comment]
Can you confirm the below implementation of the Model to store Trials, Should I make any changes ?
```from django.db import models
class Trial(models.Model):
    name = models.CharField(max_length=255)
    metrics = models.JSONField(default=dict)
    parameters = models.JSONField(default=dict)
    circuits = models.JSONField(default=dict)
    backends = models.JSONField(default=dict)
    operators = models.JSONField(default=dict)
    artifacts = models.JSONField(default=dict)
    texts = models.JSONField(default=list)
    arrays = models.JSONField(default=dict)
```

**Comment by mickahell** [comment]
@AnsahMohammad 
There are all list of `dict` except `arrays` who is just a `list`

If it can help you, here the code of those objetcs : https://github.com/IceKhan13/purplecaffeine/blob/main/client/purplecaffeine/trial.py

**Comment by AnsahMohammad** [comment]
What database should we use? JSONField is not available in SQLite.

**Comment by mickahell** [comment]
For sure it's working with classical SQL on MySQL, then @IceKhan13 do you know which kind of db system are we going to have ?

Bonus tips : I alrealdy have an Actions making available a MySQL server for autom testing ;) 
```
- uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql database: 'darkcoffeemaker'
          mysql root password: 'root'
          mysql user: 'root'
          mysql password: 'root'
```

**Comment by IceKhan13** [comment]
@AnsahMohammad let's use Postgres. And @mickahell is right, let's use list instead of dicts as default.

**Comment by mentesniker** [comment]
Guys can you add a list which is called tags to the model?
Is going to be usefull for the widget

**Comment by IceKhan13** [comment]
https://github.com/IceKhan13/purplecaffeine/issues/24
