### ISSUE TITLE
Client: ApiBackend implementation

### ISSUE THREAD

**Issue by IceKhan13** [IceKhan13/purplecaffeine#11]
Implement `ApiBackend` which will be backend for storing trials data.

Epic https://github.com/IceKhan13/purplecaffeine/issues/2

**Comment by mickahell** [comment]
This gonna be very similar to #9, main difference gonna be, except of a `.json` file the data need to be send as payload to the API.
```python
curl_req = requests.post(url, headers=headers, json=data)
```
Same for the reading part.

#### Questions : What do we want to read from the API ? (Endpoint ?)
- Everything, always
- Only tittle
- Only get everything from 1 id
- ...

**Comment by mickahell** [comment]
poke @AnsahMohammad @IceKhan13

**Comment by IceKhan13** [comment]
Here is rough description of API https://github.com/IceKhan13/purplecaffeine/wiki#api-server
