### ISSUE TITLE
Paper: prepare joss submission structure

### ISSUE THREAD

**Issue by IceKhan13** [IceKhan13/purplecaffeine#15]
Prepare submission structure for repository for JoSS https://joss.theoj.org/

Instructions https://joss.readthedocs.io/en/latest/submitting.html

**Comment by mickahell** [comment]
How do you prepare the submission (I never really wrote a publish paper for a software) ?

**Comment by mickahell** [comment]
Oh and look, they even have an Actions to autom the update https://github.com/marketplace/actions/open-journals-pdf-generator, no need for custom Actions :D
