### ISSUE TITLE
Implementation of Jupyter Widget

### ISSUE THREAD

**Issue by IceKhan13** [IceKhan13/purplecaffeine#3]
Implement Jupyter widget to explore saved trials.

```python
from purple_caffeine import Widget, LocalBackend
Widget.render(LocalBackend(file_storage_path="./"))
```

Issues:
- https://github.com/IceKhan13/purplecaffeine/issues/6
- https://github.com/IceKhan13/purplecaffeine/issues/7

**Comment by IceKhan13** [comment]
Project that we can look as first look reference is https://github.com/TheGupta2012/qiskit-timeline-debugger/tree/main/src/qiskit_trebugger

The feedback I have is that is it turning in a spagetti code if you operate only with `ipywidgets` classes + html elements.

What I was thinking is we can use Jinja templating engine to render all dynamic html and then inject it to `ipywidgets` 🤔

**Comment by mentesniker** [comment]
checking...

**Comment by mentesniker** [comment]
If we use https://pretty-jupyter.readthedocs.io/en/latest/quickstart.html then we can create html + javascript + bootstrap + python cells
disadvantage: we need to reload one cell to load changes made on python code
![image](https://user-images.githubusercontent.com/35209340/232259296-3e9e6474-c65b-4aa4-82b7-6aafea8ca221.png)

**Comment by mentesniker** [comment]
If we use jinja + IPython then we can create html + bootstrap + python cells
disadvantage: apparently our javascript code doesn't work
![image](https://user-images.githubusercontent.com/35209340/232260694-8d167d74-cd9c-4b01-8b72-037ce0d7be86.png)

**Comment by mentesniker** [comment]
So after digging into the documentation(accordingly to https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Custom.html#models-and-views) we can do something like this:

1. create a custom value widget
2. get the values that we want to inject inside the html code inside the class
3. call the method template.render so jinja can inject our python variables into the html code
4. render our inyected code using the typescript append method

**Comment by mentesniker** [comment]
Alternatively we can do the same steps but instead of using jinja we can use OOB typescript functions to change the html template

**Comment by IceKhan13** [comment]
@mentesniker let's have any of this options implemented with simple data pagination in table widget implemented with mock data. Then we will see how it looks and we will made a decision on path forward :)

**Comment by mickahell** [comment]
@IceKhan13 can we close this one ?

**Comment by IceKhan13** [comment]
yes! 🥳  closing
