### ISSUE TITLE
Client: s3 backend

### ISSUE THREAD

**Issue by IceKhan13** [IceKhan13/purplecaffeine#33]
### What is the expected behavior?

Implement s3 backend to store trials in s3 bucket.

### Details

Client: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html

Example
```python
from purplecaffeine import S3Backend

s3_backend = S3Backend(
   bucket_name="my_trials",
   key="<API_KEY>",  # this can be env
   access_key="<API_ACCESS_KEY>" # this can be env
)
```

**Comment by AnsahMohammad** [comment]
How should the trial data be passed into the s3_backend?
Should we use the IDs of the trials from the database or the paths of the local files?

**Comment by mickahell** [comment]
You should pass the data from the Trial object.
A simple way is to do the same as it done for LocalBakend. Just you create a new class call like `S3Backend` with a `save`, `get` and `list` functions to save a Trial object into S3 and to get a Trial object from S3.

Look here for LocalBackend structure : https://github.com/IceKhan13/purplecaffeine/blob/main/client/purplecaffeine/core.py#L204
