### ISSUE TITLE
Client: local backend fails if trial name does not exists

### ISSUE THREAD

**Issue by IceKhan13** [IceKhan13/purplecaffeine#35]
### Steps to reproduce the problem

```python
backend = LocalBackend("<...>")
backend.get("bla-bla") # non existing name
```
### What is the current behavior?

<img width="844" alt="Screenshot 2023-05-12 at 12 23 18 PM" src="https://github.com/IceKhan13/purplecaffeine/assets/8796709/78478e9b-da29-4af4-8134-73b12c7e3aa9">

### What is the expected behavior?

should log warning and return `None` or something :)

**Comment by mickahell** [comment]
Ok, I'll take it after my actual PR
