### ISSUE TITLE
Ecosystem: Create the submission into Qiskit Ecosystem

### ISSUE THREAD

**Issue by mickahell** [IceKhan13/purplecaffeine#69]
### What is the expected enhancement?

- [x] Make the submission into the Qiskit Ecosystem : [Submission form](https://github.com/qiskit-community/ecosystem/issues/new?labels=&template=submission.yml&title=%5BSubmission%5D%3A+)
- Add badge into readme

**Comment by mickahell** [comment]
Wait until paper is submitted

**Comment by IceKhan13** [comment]
![Screenshot 2023-06-19 at 6 26 58 PM](https://github.com/IceKhan13/purplecaffeine/assets/8796709/6a33e14c-2ebf-48e2-98a9-5fcabad02308)

We can move with it now :)

**Comment by mickahell** [comment]
https://github.com/qiskit-community/ecosystem/pull/402

**Comment by mickahell** [comment]
Project added into Ecosystem, waiting for badge generation
