### ISSUE TITLE
Client: Trial class implementation

### ISSUE THREAD

**Issue by IceKhan13** [IceKhan13/purplecaffeine#8]
Implement Trial class.

Methods for Trial class
```python
def add_metric(self, name: str, value: float):
   ...
def add_parameter(self, name: str, value: str):
   ...
def add_circuit(self, name: str, circuit: QuantumCircuit):
   ...
def add_backend(self, name: str, backend: Backend):
   ...
def add_operator(self, name: str, operator: Operator):
   ...
def add_artifact(self, name: str, path_to_file: str):
   ...
def add_text(self, text: str):
   ...
def add_array(self, array: Union[np.ndarray, List[Any]):
    ...
```

Epic https://github.com/IceKhan13/purplecaffeine/issues/1

**Comment by mickahell** [comment]
Do we have any idea of format for `input / output` in order to start ?
I mean in a basic circuit like :
```
0>------[H]-------o-------
                  |
0>--[teta*pi/5]--[x]-------
```

How do we register this circuit ?
Do we register :
- the number of qubit
- their phase at the start
- the gates and the rotation type
- order of operation
- measurement
- seed used ? 
- ... etc

And how / do we register the result or the circuit ?

I found this in the Qiskit doc to export and import a circuit : https://qiskit.org/documentation/apidoc/qpy.html

**Comment by IceKhan13** [comment]
We have metrics, parameters and text fields. We can store any information there.

For example:
```python
with Trial("my_trial") as trial:
     number_qubits = 5
     depth = 5
     circuit = random_circuit(number_qubits, depth)
     sampler = Sampler()
     result = sampler.run(circuit).result().values
    
     trail.add_metric("num_qubits", number_qubits)
     trail.add_metric("depth", depth)
     trial.add_circuit("my_circuit", circuit)
     trial.add_text("description", "THis is our awesome experiment.")
     trial.add_array("results", result)

```

**Comment by mickahell** [comment]
Questions :
- Operator: concern Quantum Operator ([Qiskit doc](https://qiskit.org/documentation/stubs/qiskit.quantum_info.Operator.html)) only or do you have something more in mind ?
- Parameters: Do you mean parameters for Gates ([Qiskit doc](https://qiskit.org/documentation/stubs/qiskit.circuit.Parameter.html))?
- Artifacts: Do we want to stock entire files or just the path ?

I see you suggested a method `add_backend()` but this gonna be init from `my_trial = Trial("toto", my_toto_backend)` so we don't need it, do we ? Or do you mean the backend for the quantum platform (like qasm) ?

**Comment by IceKhan13** [comment]
@mickahell legit questions :) 

>Operator: concern Quantum Operator ([Qiskit doc](https://qiskit.org/documentation/stubs/qiskit.quantum_info.Operator.html)) only or do you have something more in mind ?

Yes, I mean that operator

> Parameters: Do you mean parameters for Gates ([Qiskit doc](https://qiskit.org/documentation/stubs/qiskit.circuit.Parameter.html))?

No, here I've ment just any general parameter that might be used, like 
```python
with Trial() as trial:
    trial.add_parameter("meta_os", "Ubuntu")
```

> Artifacts: Do we want to stock entire files or just the path ?

Yes, we need to store entire files. Probably need to introduce some limitation for format. Something like images, json, yamls and no more than 5 mb

> add_backend()

This should be [qiskit.provider.backend.BaseBackend](https://qiskit.org/documentation/stubs/qiskit.providers.Backend.html#backend). Not our backend :)
