### ISSUE TITLE
Client: Local backend

### ISSUE THREAD

**Issue by IceKhan13** [IceKhan13/purplecaffeine#9]
Implement `LocalBackend` which will store trials on local disk in form of files.

Epic https://github.com/IceKhan13/purplecaffeine/issues/1

**Comment by mickahell** [comment]
For the client, what is the difference between local and remote backend ?

**Comment by IceKhan13** [comment]
They both inherit `BaseBackend`, think of it as strategy pattern, so Trial is picking behavior based on priovided backend

**Comment by mickahell** [comment]
Oooh I think I see what you mean, we will have a another main endpoint for the lib who gonna call the backend something like : 
```python
from client import Trial
from client.backend import Remote, Local
```

**Comment by mickahell** [comment]
@IceKhan13 for local backend, do we want one jsonfile per trial or a big jsonfile for every trial ? I have the feeling that 1 per trial would be the most useful but I'm not sure

Also as the circuits can be very big
