### ISSUE TITLE
API service: add tests

### ISSUE THREAD

**Issue by IceKhan13** [IceKhan13/purplecaffeine#99]
### What is the expected enhancement?

Add endpoint tests for API service. 

Ref: https://www.django-rest-framework.org/api-guide/testing/#api-test-cases

Required to address JoSS review comments https://github.com/openjournals/joss-reviews/issues/5673#issuecomment-1679076266

**Comment by mickahell** [comment]
- unit test @mickahell 
- CI/tox @mickahell
